version: '3.8'

services:
  postgres:
    image: postgres
    container_name: rockexploration-postgres
    environment:
      POSTGRES_DB: rockexplorationDBbands
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hardcore8*
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: rockexploration-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: mendes_j27@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: hardcore8*
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: