import "./index.css"

import type { Metadata } from "next"
import { Nunito } from "next/font/google"

import { RootLayoutProps } from "@/interfaces"

import { Providers } from "./providers"

const nunito = Nunito({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="pt-BR">
      <body className={`${nunito.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
